name: UDPCore
description: "UDPCore: Fast, seamless ESP device control for robotics and IoT via UDP."


publish_to: 'none'
version: 1.0.3+4



environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"



  flutter_lints: ^5.0.0
  shared_preferences: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

#     - family: Schyler
#       fonts:
#         - asset: fonts/Schyler-Regular.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21